services:
  - type: web
    name: pathos-emotion-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OMP_NUM_THREADS
        value: 1
      - key: MKL_NUM_THREADS
        value: 1
